enum EnvNames {
  APP_COOKIE_SECRET = "APP_COOKIE_SECRET",
  APP_MAP_TILE_URL = "APP_MAP_TILE_URL",
  APP_BASE_URL = "APP_BASE_URL",
  DENO_ENV = "DENO_ENV",
  POSTGRES_DB = "POSTGRES_DB",
  POSTGRES_HOST = "POSTGRES_HOST",
  POSTGRES_USER = "POSTGRES_USER",
  POSTGRES_PASSWORD = "POSTGRES_PASSWORD",
  POSTGRES_PORT = "POSTGRES_PORT",
  DISCORD_CLIENT_ID = "DISCORD_CLIENT_ID",
  DISCORD_CLIENT_SECRET = "DISCORD_CLIENT_SECRET",
}

export default EnvNames;
