networks:
  fresh_spots:
    driver: bridge
    ipam:
      config:
        - subnet: 169.254.173.0/24
          gateway: 169.254.173.1
services:
  workspace:
    build: 
      context: .
      dockerfile: Dockerfile
    privileged: true
    platform: linux/arm64
    ipc: host
    volumes:
      - source: extensions
        target: /home/vscode/.vscode-server/extensions
        type: volume
      - source: server-insiders
        target: /home/vscode/.vscode-server-insiders/extensions
        type: volume
      - source: /var/run/docker.sock
        target: /var/run/docker.sock
        type: bind
      - ..:/workspace:cached
    env_file:
      - .env
    environment:
      - POSTGRES_HOST=db.fresh-spots.com
    networks:
      fresh_spots:
        aliases:
          - app.fresh-spots.com
  prostgres:
    image: postgis/postgis
    restart: always
    volumes:
      - db-data:/var/lib/postgresql/data
    env_file:
      - .env
    ports:
      - ${POSTGRES_PORT}:5432
    networks:
      fresh_spots:
        aliases:
          - db.fresh-spots.com
  adminer:
    depends_on:
      - prostgres
    image: adminer
    restart: always
    ports:
      - 8090:8080
    networks:
      fresh_spots:
        aliases:
          - adminer.fresh-spots.com
volumes:
  extensions:
  server-insiders:
  db-data: