networks:
  fresh_spots:
    driver: bridge
    ipam:
      config:
        - subnet: 169.254.173.0/24
          gateway: 169.254.173.1
services:
  workspace:
    build: 
      context: .
      dockerfile: Dockerfile
    privileged: true
    platform: linux/arm64
    ipc: host
    volumes:
      - source: extensions
        target: /home/vscode/.vscode-server/extensions
        type: volume
      - source: server-insiders
        target: /home/vscode/.vscode-server-insiders/extensions
        type: volume
      - source: /var/run/docker.sock
        target: /var/run/docker.sock
        type: bind
      - ..:/workspace:cached
    env_file:
      - .env
    networks:
      fresh_spots:
        ipv4_address: 169.254.173.2
        aliases:
          - workspace.fresh-spots.com
volumes:
  extensions:
  server-insiders: