networks:
  instastar:
    driver: bridge
    ipam:
      config:
        - subnet: 169.254.171.0/24
          gateway: 169.254.171.1
services:
  op-connect-api:
    image: 1password/connect-api:latest
    volumes:
      - "./home/1password-credentials.json:/home/opuser/.op/1password-credentials.json"
      - "op_data:/home/opuser/.op/data"
    networks:
      instastar:
        ipv4_address: 169.254.171.2
  op-connect-sync:
    image: 1password/connect-sync:latest
    volumes:
      - "./home/1password-credentials.json:/home/opuser/.op/1password-credentials.json"
      - "op_data:/home/opuser/.op/data"
    networks:
      instastar:
        ipv4_address: 169.254.171.3
  workspace:
    build: 
      context: .
      dockerfile: Dockerfile
    privileged: true
    ipc: host
    volumes:
      - source: extensions
        target: /home/vscode/.vscode-server/extensions
        type: volume
      - source: server-insiders
        target: /home/vscode/.vscode-server-insiders/extensions
        type: volume
      - source: /var/run/docker.sock
        target: /var/run/docker.sock
        type: bind
      - ..:/workspace:cached
    environment:
      - OP_CONNECT_HOST=http://op-connect-api:8080
    env_file:
      - .env
    networks:
      instastar:
        ipv4_address: 169.254.171.4
        aliases:
          - workspace.fresh-spots.com
  # db:
  #   image: mongo:latest
  #   restart: unless-stopped
  #   volumes:
  #     - mongodb-data:/data/db
  #   # Uncomment to change startup options
  #   environment:
  #    MONGO_INITDB_ROOT_USERNAME: root
  #    MONGO_INITDB_ROOT_PASSWORD: example
  #    MONGO_INITDB_DATABASE: your-database-here
  #   networks:
  #     local:
  #       ipv4_address: 169.254.171.5
volumes:
  extensions:
  server-insiders:
  op_data: